language: c
script: make && make fs.img
deploy:
  provider: releases
  api_key:
    secure: IYscjWfFXKsXnMBTUo3KaKjuj5/3Zf7X7nXb+bPRG2rI1gs/N/sEaCg7gdfJPBBXA4dGitFzXjA44dhJPyWMLl2BzeY2p9yBMKVRj67cqjXhGoNvCWZiYP12J450lrhBbuP4yoopUbOLlLINRKfjt/uUL0VmkqK/tChxQ8DjscX1a+6mSLbCs86bnVxdU5R5ybhz2NM/VtbMZGdM84OBts9tyFu606zTXsitbvifawOuiOHrIT7jZ22C7IZk8tGY8VU9OU+5nkdC9EFyz23XDbQfE5RHCH/6kOLRXc5HpiTVhSONHIXGeO+zDTbRexesTcaA4qX2Wy3iOeG3/K/pSpzdbKRZKSznEBe09JV1sKrjoR6Vfo+837f2JJRTF9xUN4Ebjyi2ym9qvJrNeWQDnhcN+Jwz8MphqT1Ba3+/GLDgV4ajH6Joa5DHGZ6/N5/Pwd83+LAahOj9vdQAlITcJ00Cqbl2RhJ9KEuHjnIZBKIWR8l0P3IYsXCb1ySuFv7Z31bcd6TI0aCSqX2ydSNUtLt82fLeoDaGorJeBBjrbdqoYKs1EGCm7f3uEP0oz5uUf2z0udTAZ1Erub2b8znBiG9ofUV30fhBYJQW2E33GH+KW8BR/rN7VUqGiALDZDdQBuWx/1TF3fZOnVEUg30IfZ+U+KO7E1JRWCtaj0f722E=
  file:
      - fs.img
      - xv6.img
  skip_cleanup: true
  on:
    repo: jafemm/xv6-public
    branch: project_1
    tags: true
