language: c
script: make && make fs.img
deploy:
  provider: releases
  api_key:
    secure: rWzKJgdPnkk2sv0iByQctJcAoEhHGZt5rVBBJwk8gS229f5QX08LTxuWEUf/PT3nB+Vk4amct4qR2ppIrT3K0nECq7hcIPNxvok2IT51PLhwbF+3m8ICMObSOU/8yoRlCzEOilb5N5plAkua5PpV4waIa17YmlTxWnSGpE1KG0ZDRtKbVCpYBRxFQ0J16YMxBxHhzuVOaUTN6k0+c5P/6DIt3UkHgoDkn5+npTOK40CYbC58k9T0UJKwTWwxKsU9JjdCOZSdJJLQW3ThOu0RXYTmkUMmOV9dXA/7PfBMFZHLhBtO9JWNJMzkqFDAzcXA0vchETm8Akl+KJb/qZcBMWnSBhk8C6lqETIBhdqUhG6xoyGHPOcPguUc9r1jU15lVrqe+M6D3EuSFDZfEwjl1iJ3OznLZgQKNXNAOBsBkbftydze6i42Md5uqfH6nGu56uyS4A2ZDaY22oFiHbFD1C4A1HeMfKRIhcykaiGpq47IKLj5hNsb3G++5/oIHpeu5WLHd+GhofYkY13gkyL1ECrxFPmPc9u8PR5FuAqbqGjcmZyWxrDJKcmgwFfgc2bOAdy66vaWZmVmHvqt6azUlm0F0eBxtN9itV91v8PJ+AfYPCaEwbmLulEFMQppmlTRDnSN4x+vRYt1zfen9/pzdaR3MvuxKn14IZt3fpLbFW0=
  file:
      - fs.img
      - xv6.img
      skip_cleanup: true
  on:
    repo: jafemm/xv6-public
    branch: heads/master
    tags: true
